POST http://localhost:5173/api/manage/integrations/enable
Content-Type: application/json

{
    "platform": "telegram"
}


###
POST http://localhost:5173/api/manage/integrations/disable
Content-Type: application/json

{
    "platform": "telegram"
}

### Get all integrations
GET http://localhost:5173/api/manage/integrations
